# https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
version: 0.2
env:
  variables:
    SBT_VERSION: "1.4.0"
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo `pwd`
      - curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
      - dpkg -i sbt-$SBT_VERSION.deb
      - sbt sbtVersion
      - sbt website/run
artifacts:
  files:
    - '**/*'
  base-directory: $WEBSITE_TARGET
