version: 0.1

phases:
  pre_build:
    commands:
      - git rev-parse --short HEAD > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --tag "$(cat /tmp/build_tag.out)" build-images/
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
