# https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
# Set the KMS_KEY_ID and BUCKET_NAME parameters.
version: 0.2
env:
  variables:
    INPUT: "lambda/input.cfn.yml"
    OUTPUT: "lambda/output.cfn.yml"
phases:
  install:
    commands:
      - echo `pwd`
      - npm install time
      - aws cloudformation package --template-file $INPUT --kms-key-id $KMS_KEY_ID --s3-bucket $BUCKET_NAME
        --output-template-file $OUTPUT
artifacts:
  type: zip
  files:
    - $INPUT
    - $OUTPUT
    - node_modules/**/*
