# https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
# Set the KMS_KEY_ID and BUCKET_NAME parameters.
version: 0.2
env:
  variables:
    INPUT: "input-slim.cfn.yml"
    OUTPUT: "output.cfn.yml"
phases:
  install:
    commands:
      - cd lambda
      - echo `pwd`
      - npm install time
      - aws cloudformation package --template-file $INPUT --s3-bucket $BUCKET_NAME
        --output-template-file $OUTPUT
      # Consider adding '--kms-key-id $KMS_KEY_ID' if I figure out how to give use-rights to the key in CloudFormation
artifacts:
  type: zip
  files:
    - $OUTPUT
  base-directory: lambda
