AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: A Lambda function conditionally triggered by a schedule.

Parameters:

  ScheduleExpression:
    Type: String
    Description: Schedule expression (empty for no schedule)
    Default: "rate(10 minutes)"

Conditions:

  IsScheduled: !Not [ !Equals [ !Ref ScheduleExpression, "" ] ]

Resources:

  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./

  ScheduledRule:
    Type: AWS::Events::Rule
    Condition: IsScheduled
    Properties:
      Description: "Invokes the Lambda function according to schedule"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt TimeFunction.Arn
          Id: "TimeFunctionV1"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Condition: IsScheduled
    Properties:
      FunctionName:
        Ref: TimeFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn
