---
AWSTemplateFormatVersion: 2010-09-09

Description: Redis

# Creates Redis.

Parameters:

  CacheNodeType:
    Description: The compute and memory capacity of the nodes in the node group (shard)
    Type: String
    Default: cache.t2.micro
    # https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m3.medium
      - cache.m3.large
      - cache.m3.xlarge
      - cache.m3.2xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.r3.large
      - cache.r3.xlarge
      - cache.r3.2xlarge
      - cache.r3.4xlarge
      - cache.r3.8xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge

  NumCacheNodes:
    Description: The number of cache nodes that the cache cluster should have
    Type: Number
    Default: 1

  NetworkStackName:
    Description: Name of an active CloudFormation stack of networking resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

Resources:

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Cache subnet group
      SubnetIds:
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet1ID
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet2ID

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref CacheNodeType
      NumCacheNodes: !Ref NumCacheNodes
      Engine: redis
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub ${NetworkStackName}-RedisGroupID
      CacheSubnetGroupName: !Ref SubnetGroup

Outputs:

  Name:
    Description: Redis Stack Name
    Value: !Ref RedisCluster
    Export:
      Name: !Sub ${AWS::StackName}-Name

  RedisAddress:
    Description: Redis Address
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-Address

  RedisPort:
    Description: Redis Port
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-Port
