name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Install AWS CDK
        run: |
          sudo npm install -g aws-cdk@1.132.0
          cdk --version
      - name: Run tests
        run: sbt test
      - name: Validate CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
        run: |
          cdk synth
