name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: Install AWS CDK
        run: |
          sudo npm install -g aws-cdk@2.1020.0
          cdk --version
      - name: Run tests
        run: sbt test
      - name: Validate CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
        run: |
          cdk synth --notices false
